Add and improve `Guild` family packets
sorokya/eo_protocol pull request #13
Opened 2022-11-16 14:30 UTC by Cirras

2022-11-18 15:00 UTC, sorokya requested changes

2022-11-18 15:00 UTC, sorokya commented on eo.txt
> -	raw_string(3) guild_tag
Does the client pad this with spaces if it's less than 3? If so I'd rather use `raw_string(3)` followed by a `break`

2022-11-18 15:00 UTC, sorokya commented on eo.txt
> +	int = 20202
weird! the client just always sends 20202? lol

2022-11-19 01:41 UTC, Cirras commented on eo.txt
> +	int = 20202
Surprisingly, yes.
![image](https://user-images.githubusercontent.com/22178573/202828118-5a56ab69-f8e6-464c-bdbe-5d4d1dec9603.png)

2022-11-19 02:01 UTC, Cirras commented on eo.txt
> -	raw_string(3) guild_tag
As far as I can tell, the "pad with spaces thing is just something EOSERV does to not break the few packets that expect a `raw_string(3)`.
It doesn't seem like the client ever does that.

In my view, aside from the places where a literal `raw_string(3)` is expected, `string` should be used.
Yes, that technically means that a client or server could send a guild tag with some silly length, but that validation should be happening at a higher layer than the protocol definition.

2022-11-19 02:10 UTC, Cirras commented on eo.txt
> -	raw_string(3) guild_tag
Since you commented on this, I had another look and noticed 2 other spots where `raw_string(3)` was used incorrectly instead of a `string`.

2022-11-19 10:52 UTC, sorokya commented on eo.txt
> -	raw_string(3) guild_tag
Yeah I saw that the client handled it just fine without the padding. SLN breaks if you don't pad them in the playerlist though :\

2022-11-19 10:54 UTC, sorokya commented on eo.txt
> +	int = 20202
amazing

2022-11-19 10:55 UTC, sorokya commented on eo.txt
> -	raw_string(3) guild_tag
I'm not sure about these though.. `string` implies there's always a break after. Need to do some testing with GameServer to confirm

2022-11-19 12:31 UTC, sorokya commented on eo.txt
> -	raw_string(3) guild_tag
Confirmed that these packets do not pad spaces so should be fine. The server packet for online list does however.

2022-11-19 13:13 UTC, sorokya commented on eo.txt
> -	raw_string(3) guild_tag
Confirmed there is a `break` after tag

2022-11-19 13:15 UTC, merged